#!/usr/bin/env python3
"""
Financial News Analyzer with Claude
Uses Claude's built-in web search to find and analyze today's macro news
Sends analysis via email
"""

import os
import smtplib
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import anthropic

client = anthropic.Anthropic()


def analyze_with_claude():
    """
    Use Claude with web search to find and analyze today's macro news
    """
    today = datetime.now().strftime("%B %d, %Y")

    prompt = f"""Today is {today}. Please search the web for today's most important macro financial news and then provide a detailed briefing covering:

1. **Key Market Movers**: The most significant stories moving markets today and their immediate implications
2. **Fed & Rates**: Any Fed speak, rate expectations, or Treasury market developments
3. **Inflation & Economic Data**: Any data releases today (CPI, PPI, jobs, GDP, PMI, etc.)
4. **FX & Cross-Asset**: Notable currency moves and cross-asset implications
5. **Trading Insights**: Concrete trading themes or opportunities from today's news
6. **Tail Risks**: Key risks or unknowns to watch in the near term

Be specific — include actual numbers, yield levels, and price moves where available. This is for a macro rates trader at a bulge bracket bank."""

    response = client.messages.create(
        model="claude-sonnet-4-5",
        max_tokens=4000,
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        system="""You are a macro rates trading analyst at a bulge bracket investment bank. 
You have deep expertise in fixed income, rates trading, Fed policy, and cross-asset macro.
When analyzing news, always include specific data points, yield levels, and price moves.
Your briefings are read by senior traders who need actionable, specific insights — not generic commentary.""",
        messages=[{"role": "user", "content": prompt}],
    )

    # Extract the final text response (after web search tool use)
    analysis = ""
    for block in response.content:
        if block.type == "text":
            analysis += block.text

    return analysis


def send_email(analysis):
    """Send the analysis via Gmail"""
    sender_email = "zeke.abramowicz8@gmail.com"
    recipient_email = "zeke.abramowicz8@gmail.com"
    app_password = os.getenv("GMAIL_APP_PASSWORD")

    if not app_password:
        print("Error: GMAIL_APP_PASSWORD environment variable not set")
        return False

    try:
        message = MIMEMultipart()
        message["From"] = sender_email
        message["To"] = recipient_email
        message["Subject"] = f"Daily Macro Briefing — {datetime.now().strftime('%B %d, %Y')}"

        html_body = f"""
        <html>
            <body style="font-family: Arial, sans-serif; line-height: 1.6; max-width: 800px; margin: auto; padding: 20px;">
                <h2 style="color: #1a1a2e;">📈 Daily Macro Rates Briefing</h2>
                <p style="color: #666;"><em>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}</em></p>
                <hr style="border: 1px solid #eee;">
                <div style="white-space: pre-wrap; word-wrap: break-word; font-size: 14px;">
{analysis}
                </div>
                <hr style="border: 1px solid #eee;">
                <p style="color: #999; font-size: 12px;">Generated by Claude with live web search.</p>
            </body>
        </html>
        """

        message.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender_email, app_password)
            server.send_message(message)

        print(f"✓ Email sent successfully to {recipient_email}")
        return True

    except smtplib.SMTPAuthenticationError:
        print("Error: Gmail authentication failed. Check your app password.")
        return False
    except Exception as e:
        print(f"Error sending email: {e}")
        return False


def main():
    print("=" * 60)
    print("Daily Macro Briefing — Claude with Web Search")
    print(f"Run time: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}")
    print("=" * 60)

    print("Searching and analyzing today's macro news...")
    analysis = analyze_with_claude()

    print("\n" + "=" * 60)
    print("ANALYSIS")
    print("=" * 60)
    print(analysis)

    print("\nSending email...")
    send_email(analysis)


if __name__ == "__main__":
    main()
